language: node_js
node_js: '0.12'
after_script: rm /tmp/*.json; istanbul cover ./node_modules/mocha/bin/_mocha --report
  lcovonly -- -R spec && ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
  < ./coverage/lcov.info && rm -rf ./coverage
deploy:
  provider: npm
  email: manuelmachadomartins@gmail.com
  api_key:
    secure: evmsmkP+491FlNO3poyWbYpidJSGhxww3Cpp5CUawhtDuGryLJMw8ju/WTm3VzTLyJuCmBrajVcGyCmgzHa5ljQR+iH/K9FGvij7JttXB7QJrwk5f6nopG9k2nyh2kMVXtjjbpFPdTQbt0Zg8yLidfwzAN0l27yXGIjD/EkpCPppeSci2PAqG0q9lUAiJmHN1ZEEzu0hzR0b7nTmH5tDGRTk4UPK8QGbeGK82W2x6qWMZEIH9FTRkFT8mK3i4vUqD3AsNy/PQGU5zKudrIt0IsYNh7bH8CScrT4b3eZma1P1vHtaYcGzRr7ynfUa2KATdQ6aAtmVk7fzWJzvNoZ1H7KGY1pG8wk3lCXHxFN9+BM5FMC2E/S4qLI/tn42o98Id7vsoSk2SX7Wfi4J2JuoElzE1n8RQ0WjOF5+xLICvSjzYExSlZtis+tqrSLjD2YbxzJD1SAugEqQjY+8axMLg9r+9zeWwE4sWIWVaZRRoDHsVGsynr7OGPHMvwARW63brqTYKc4te6FQYKxyeSgkET1hd/XKBFpA4HQzt3YZzsF4fkHHo5c4UzDLV8GvC+L3HN2+VtvS5ZnCpXyQ38KV08YJtldYuLo5q9wzYuXf6I3uXcSBbAFzCwUjkhI+uRAmyiAuw1pM3/IopsTtzw3AGcddlAqMqHVIbndQiehpD+4=
  on:
    tags: true
    repo: mcmartins/jsondbfs
